# Generated by Django 2.2.6 on 2019-11-13 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import seguridad.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('zipcode', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('avatar', models.ImageField(null=True, upload_to=seguridad.models.get_file_path)),
                ('access_code', models.IntegerField(null=True)),
                ('account_validated', models.IntegerField(null=True)),
                ('free_raider', models.IntegerField(blank=True, null=True)),
                ('email_sender', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile',
                'managed': True,
            },
        ),
    ]
