# Generated by Django 2.2.6 on 2019-11-13 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.CharField(max_length=255, unique=True)),
                ('acceptcomments', models.IntegerField(db_column='acceptComments')),
                ('hashtag', models.TextField()),
                ('maxopinions', models.IntegerField(db_column='maxOpinions')),
                ('maxopinionsmobile', models.IntegerField(db_column='maxOpinionsMobile')),
                ('treefilekey', models.TextField(blank=True, db_column='treeFileKey', null=True)),
                ('backgroundfilekey', models.TextField(blank=True, db_column='backgroundFileKey', null=True)),
                ('messagefilekey', models.TextField(blank=True, db_column='messageFileKey', null=True)),
                ('filepath', models.TextField(blank=True, db_column='filePath', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('share_facebook', models.IntegerField()),
                ('share_twitter', models.IntegerField()),
                ('manual', models.TextField()),
                ('show_in_home', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'topic',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('color', models.TextField()),
                ('rotation', models.TextField()),
                ('browser', models.CharField(max_length=255)),
                ('platform', models.CharField(max_length=255)),
                ('clientip', models.CharField(db_column='clientIP', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('like_opinion', models.IntegerField()),
                ('not_like_opinion', models.IntegerField()),
                ('share_facebook', models.IntegerField()),
                ('share_twitter', models.IntegerField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.Topic')),
            ],
            options={
                'db_table': 'opinion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('opinion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.Opinion')),
            ],
            options={
                'db_table': 'comment',
                'managed': True,
            },
        ),
    ]
